# DashScopeImageController类的image方法
POST http://localhost:8999/api/image/editByUrl?url=http://dxcdn.bookspxyc.xyz/111.jpg

###
# DashScopeImageController类的multipleConditions方法
GET http://localhost:10008/example/image/multipleConditions
